<form action="/auth/login" method="post" class="form">
    <header class="form__header">
        <p class="form__title">Вход</p>
    </header>
    <main class="form__main">
        <input type="hidden" name="csrf" value="<?= $csrf; ?>">
        <label for="email" class="label">Почта</label>
        <input type="email" name="email" id="email" class="form__input">
        <label for="password" class="label">Пароль</label>
        <input type="password" name="password" id="password" class="form__input">
        <button type="submit" class="form__button">Войти</button>
    </main>
</form>