<form action="/auth/login/handler" method="post" class="form">
    <header class="form__header">
        <p class="form__title">Вход</p>
    </header>
    <main class="form__main">
        <input type="hidden" name="csrf" value="<?= $csrf; ?>">
        <div class="wrapper">
            <label for="email" class="label">Почта</label>
            <input type="email" name="email" id="email" class="form__input">
            <div class="error"></div>
        </div>
        <div class="wrapper">
            <label for="password" class="label">Пароль</label>
            <input type="password" name="password" id="password" class="form__input">
            <div class="error"></div>
        </div>
        <div class="wrapper">
            <label for="remember" class="label">Запомнить</label>
            <input type="checkbox" name="remember" id="remember" class="form__checkbox" checked>
        </div>
        <button type="submit" class="form__button">Войти</button>
    </main>
</form>