<main class="main">
    <div class="form-wrapper">
        <form action="" method="post" class="form" name="login">
            <header class="form-header">Login</header>
            <main class="form-main">
                <input type="hidden" name="csrf" value="<?= $csrf ?>">
                <div class="input-wrapper">
                    <label for="email" class="input-label email-label"></label>
                    <input type="email" id="email" name="email" placeholder="Email" class="input" autocomplete="off">
                </div>
                <div class="input-wrapper">
                    <label for="password" class="input-label password-label"></label>
                    <input type="password" id="password" name="password" placeholder="Password" class="input" autocomplete="off">
                    <div class="toggle hide"></div>
                </div>
                <div class="checkbox-wrapper">
                    <input type="checkbox" id="remember" name="remember" class="checkbox" checked>
                    <label for="remember" class="checkbox-label remember-label">Remember me</label>
                </div>
                <button type="submit" class="form-submit">Sign in</button>
            </main>
            <footer class="form-footer">
                <div class="error"></div>
            </footer>
        </form>
        <form action="/vk" method="post" name="vk">
            <input type="hidden" name="csrf" value="<?= $csrf ?>">
            <button type="submit" class="vk"></button>
        </form>
    </div>
</main>


<script src="/assets/js/func.js"></script>
<script src="/assets/js/log.js"></script>
