<main class="main">
    <div class="form-wrapper">
        <form action="" method="post" class="form" name="registration">
            <header class="form-header">Registration</header>
            <main class="form-main">
                <input type="hidden" name="csrf" value="<?= $csrf ?>">
                <div class="input-wrapper">
                    <label for="username" class="input-label username-label"></label>
                    <input type="text" id="username" name="username" placeholder="Username" class="input" autocomplete="off">
                    <div class="input-help username-help">Enter your name</div>
                </div>
                <div class="input-wrapper">
                    <label for="email" class="input-label email-label"></label>
                    <input type="email" id="email" name="email" placeholder="Email" class="input" autocomplete="off">
                    <div class="input-help email-help">Enter your email address</div>
                </div>
                <div class="input-wrapper">
                    <label for="password" class="input-label password-label"></label>
                    <input type="password" id="password" name="password" placeholder="Password" class="input" autocomplete="off">
                    <div class="toggle hide"></div>
                    <div class="input-help password-help">Password must be at least 8 characters long, contain at least one lowercase letter, one uppercase letter and one number</div>
                </div>
                <div class="input-wrapper">
                    <label for="confirm" class="input-label confirm-label"></label>
                    <input type="password" id="confirm" name="confirm" placeholder="Confirm password" class="input" autocomplete="off">
                    <div class="input-help confirm-help">Repeat password</div>
                </div>
                <button type="submit" class="form-submit">Sign up</button>
            </main>
            <footer class="form-footer">
                <div class="error"></div>
            </footer>
        </form>
    </div>
</main>

<script src="/assets/js/func.js"></script>
<script src="/assets/js/reg.js"></script>