<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/assets/css/style.css">
    <title>Document</title>
</head>
<body>
    <header class="header">
        <nav>
            <ul class="nav">
                <li><a href="/" class="nav__a">Home</a></li>
                <li><a href="/auth/register" class="nav__a">Register</a></li>
                <li><a href="/auth/login" class="nav__a">Login</a></li>
                <li><a href="/auth/logout" class="nav__a">Logout</a></li>
                <li><a href="/dashboard" class="nav__a">Dashboard</a></li>
            </ul>
        </nav>
    </header>
    <main class="main">
        <?php include VIEW . $contentView ?>
    </main>
    <footer class="footer"></footer>
</body>
</html>