<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/assets/css/style.css">
    <title>Document</title>
</head>
<body>
    <section class="container">
        <header class="header">
            <nav>
                <ul class="nav">
                    <li><a href="/" class="nav-a">Home</a></li>
                    <?php if (empty($_SESSION['loggedin'])):  ?>
                        <li><a href="/auth/register" class="nav-a">Sign Up</a></li>
                        <li><a href="/auth/login" class="nav-a">Sign In</a></li>
                    <?php else: ?>
                        <li><a href="/dashboard" class="nav-a">Dashboard</a></li>
                        <li><a href="/content" class="nav-a">Content</a></li>
                        <li><a href="/auth/logout" class="nav-a">Logout</a></li>
                    <?php endif; ?>
                </ul>
            </nav>
        </header>
        <main class="main">
            <?php include VIEW . $contentView ?>
        </main>
        <footer class="footer"></footer>
    </section>
</body>
</html>